teste/pages/urls.py
from django.urls import path
from .views import UsuarioCreate
from .import views
from .views import List
app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("registrar/", UsuarioCreate.as_view(), name="registrar" ),
    path("listar/", List.as_view(), name="listar" ),
]

teste/teste/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path("", include("pages.urls", namespace="pages")),

]

teste/pages/models.py
from django.db import models

# Create your models here.

teste/pages/forms.py
from django import forms
from django.contrib.auth.forms import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
    nascimento = forms.DateField()

    class Meta:
        model = User
        fields = ['username', 'nascimento']

teste/pages/views.py
from django.views.generic import  TemplateView
from django.views.generic import CreateView
from django.contrib.auth.models import User
from .forms import UserForm
from django.urls import reverse_lazy
from django.views.generic.list import ListView


class HomePageView(TemplateView):
    template_name = "home.html"

class UsuarioCreate(CreateView):
   success_url = reverse_lazy("account_login")
   template_name = "account/signup.html"
   form_class = UserForm

class List(ListView):
    model = User
    template_name = "listagem.html"

teste/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">lista de usuarios</a>
                <ul class="navbar-nav">

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">baixar dados</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:listar' %}">cadastrados</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:registrar' %}">Cadastro</a>
                    </li>

                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

teste/templates/home.html
{% extends 'base.html' %}

{% block title %}lista de cadastrados{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h1>nao sei oque por </h1>
{% else %}
<div class="conteiner" align="center">
    <h1>entre ou cadastre-se para acessar a base de dados</h1>
</div>
{% endif %}
{% endblock %}

teste/templates/listagem.html
{% extends 'base.html' %}
{% block title %}lista de cadastrados{% endblock %}
{% block content %}
{% load static %}

<h1>todos os cadastrados</h1>
<hr>
<table class="table table-striped">
   <tr>
       <th>nome</th>



   </tr>
    {% for user in object_list %}
    <tr>
        <td>{{user.username}}</td>

    </tr>
    {% empty %}
    <tr>
        <td colspan="3">nenhum campo registrado</td>
    </tr>
    {% endfor %}

</table>
{% endblock %}